SELECT DISTINCT SCOMPANIA,TIPO_RA,GRUPO_RA,NTIPO_NOMINA,DFECHA_FINAL_PERIODO,APROBACION,ACTUALIZADO_CONTAB,CONTABILIZADO,CONTABILIZAR
FROM bintablas b,
(SELECT DISTINCT SCOMPANIA,TIPO_RA,GRUPO_RA,NTIPO_NOMINA,DFECHA_FINAL_PERIODO,APROBACION,ACTUALIZADO_CONTAB,
 CONTABILIZADO,CONTABILIZAR
 FROM RH_LM_RA R
 WHERE APROBACION  =   'S'
 AND TIPO_RA IN('1','2','4')  
 AND 0 = (SELECT COUNT(1) FROM RH_LM_RA R1 
          WHERE R1.SCOMPANIA = R.SCOMPANIA 
            AND R1.VIGENCIA = R.VIGENCIA 
            AND R1.TIPO_RA = R.TIPO_RA 
            AND R1.NTIPO_NOMINA = R.NTIPO_NOMINA 
            AND R1.DFECHA_INICIAL_PERIODO = R.DFECHA_INICIAL_PERIODO 
            AND R1.NRO_RA_OPGET IS NULL)) n
WHERE b.grupo = 'NOMINA'
  AND b.nombre = 'RELACIONAUTORIZACION_GRUPOS_RA'
  AND instr(b.argumento, n.grupo_ra) > 0 
  AND b.vig_inicial <= sysdate
  AND (b.vig_final IS NULL OR b.vig_final >= sysdate)
  AND b.resultado <> 'CONCEJALES'  