

SELECT 'REVOKE '||GRANTED_ROLE||' FROM AIAREVALO;' 
FROM (
SELECT GRANTED_ROLE 
--, ADMIN_OPTION, DELEGATE_OPTION, COMMON, INHERITED 
FROM DBA_ROLE_PRIVS
WHERE GRANTEE = 'AIAREVALO'
--AND GRANTED_ROLE LIKE 'TRC%'
--order by 1
MINUS
SELECT GRANTED_ROLE --, ADMIN_OPTION, DELEGATE_OPTION, COMMON, INHERITED 
FROM DBA_ROLE_PRIVS
WHERE GRANTEE = 'DSANCHEZP' )
--AND GRANTED_ROLE LIKE 'TRC%'
--order  by 1
--ORDER BY GRANTED_ROLE
;

SELECT *
FROM USUARIOS_COMPANIA
WHERE USUARIO IN ('DSANCHEZP','AIAREVALO');

INSERT INTO USUARIOS_COMPANIA 
SELECT 'AIAREVALO', CODIGO_COMPANIA, PERMITIR_MODIFICAR, SISTEMA, CODIGO_UNIDAD_EJECUTORA
FROM USUARIOS_COMPANIA
WHERE USUARIO = 'DSANCHEZ' and SISTEMA='PAC'


--commit;

select *
  from bintablas bb
 where bb.grupo like 'OPGET' 
 and nombre like 'FUNC%'

REVOKE CM_ADMIN FROM AIAREVALO;
REVOKE CM_ELAB_COMPROBANTE FROM AIAREVALO;
REVOKE CORR_ADM FROM AIAREVALO;
REVOKE OGT_CONSULTA FROM AIAREVALO;
REVOKE OGT_CONSULTA_AUD_PAC FROM AIAREVALO;
REVOKE OGT_CONSULTA_ESTADO FROM AIAREVALO;
REVOKE OGT_CONSULTA_OIS FROM AIAREVALO;
REVOKE OGT_CONSULTA_USU FROM AIAREVALO;
REVOKE OGT_NO_ADMIN FROM AIAREVALO;
REVOKE OGT_SOLO_CONSULTA FROM AIAREVALO;
REVOKE PAC_ADMIN FROM AIAREVALO;
REVOKE PR_ADMIN FROM AIAREVALO;
REVOKE SL_ACREENCIAS FROM AIAREVALO;
REVOKE SL_ACTU_PERSONA FROM AIAREVALO;
REVOKE SL_ADMIN FROM AIAREVALO;
REVOKE SL_ADMIN_CP FROM AIAREVALO;
REVOKE SL_ATENCION_EAAB FROM AIAREVALO;
REVOKE SL_BONCOACTIVO FROM AIAREVALO;
REVOKE SL_CALCULO_ACTUARIAL FROM AIAREVALO;
REVOKE SL_CAP FROM AIAREVALO;
REVOKE SL_CERT_PENSION FROM AIAREVALO;
REVOKE SL_COMPROBANTE_PAGO FROM AIAREVALO;
REVOKE SL_CONSULTA_ACRE FROM AIAREVALO;
REVOKE SL_CONSULTA_HL FROM AIAREVALO;
REVOKE SL_CONSULTA_NO FROM AIAREVALO;
REVOKE SL_CONT FROM AIAREVALO;
REVOKE SL_COR_NOMINA FROM AIAREVALO;
REVOKE SL_CUOTAS_X_COBRAR_T FROM AIAREVALO;
REVOKE SL_CUOTA_CONSULTA FROM AIAREVALO;
REVOKE SL_CUOTA_PAGO FROM AIAREVALO;
REVOKE SL_CUOTA_X_COBRAR_CONTA FROM AIAREVALO;
REVOKE SL_CXC_T FROM AIAREVALO;
REVOKE SL_DESPRENDIBLE FROM AIAREVALO;
REVOKE SL_DETALLE_CAMBIOS FROM AIAREVALO;
REVOKE SL_DSI FROM AIAREVALO;
REVOKE SL_EAAB_PAGOS FROM AIAREVALO;
REVOKE SL_ENVCOACTIVO FROM AIAREVALO;
REVOKE SL_EXPEDIENTE_CONS FROM AIAREVALO;
REVOKE SL_GENERA_PLANO FROM AIAREVALO;
REVOKE SL_HIS_RECHA_BANCO FROM AIAREVALO;
REVOKE SL_LIQ_PENSION FROM AIAREVALO;
REVOKE SL_LIQ_PENSION_SOP FROM AIAREVALO;
REVOKE SL_NOMINA_EAAB FROM AIAREVALO;
REVOKE SL_NOTIFICA FROM AIAREVALO;
REVOKE SL_OIS FROM AIAREVALO;
REVOKE SL_OIS_CONSULTA FROM AIAREVALO;
REVOKE SL_PLANO_CONTA FROM AIAREVALO;
REVOKE SL_PLANO_CONTA_CONS FROM AIAREVALO;
REVOKE SL_REINT FROM AIAREVALO;
REVOKE SL_RESOL_NOTI FROM AIAREVALO;
REVOKE SL_SOPORTE_CAMBIOS FROM AIAREVALO;
REVOKE SL_SOP_JUR1 FROM AIAREVALO;
REVOKE SL_SOP_JUR2 FROM AIAREVALO;
REVOKE SL_SOP_RAD FROM AIAREVALO;
REVOKE SL_TEMP_TABLE FROM AIAREVALO;
REVOKE SL_USUARIO_ACTUALIZACION FROM AIAREVALO;
REVOKE SL_VOLANTEWEB FROM AIAREVALO;
REVOKE SL_WCC FROM AIAREVALO;
REVOKE TRC_ADMIN_GRAL_ROLE FROM AIAREVALO;
