

SELECT GRANTED_ROLE --, ADMIN_OPTION, DELEGATE_OPTION, COMMON, INHERITED 
FROM DBA_ROLE_PRIVS
WHERE GRANTEE = 'AFORTEGON'
--AND GRANTED_ROLE LIKE 'TRC%'
--order by 1
MINUS
SELECT GRANTED_ROLE --, ADMIN_OPTION, DELEGATE_OPTION, COMMON, INHERITED 
FROM DBA_ROLE_PRIVS
WHERE GRANTEE = 'VVARGASN'
--AND GRANTED_ROLE LIKE 'TRC%'
-- by 1
--ORDER BY GRANTED_ROLE
;


SELECT GRANTED_ROLE --, ADMIN_OPTION, DELEGATE_OPTION, COMMON, INHERITED 
FROM user_ROLE_PRIVS
WHERE GRANTED_ROLE LIKE 'TRC_%'

DEFINE newuser = 'VVARGASN'
DEFINE revokuser  = ''
DEFINE numregs = 999
DEFINE contrasegna  = '#F0nC3p2026#' --SELECT SUBSTR('&&newuser',1,2)||to_char(sysdate,'YYYYMMDD') FROM dual
select '&&newuser','&&contrasegna' from dual

ACCEPT newname PROMPT 'Nombre del Usuario '
ACCEPT newuser PROMPT 'Usuario a Crear (Primeras letras de nombres y el primer apellido: '
ACCEPT contrasegna


prompt "terminado"


--drop user  &&newuser

-- Create the user for PERNO module. ERP SiC@pital
create user &&newuser identified by '#F0nC3p2026#';

grant connect to &&newuser with admin option;

GRANT  'TRC_ADMIN_GRAL_ROLE' TO &&newuser ;

----En teoria no se requieren mas roles.

-- Grant/Revoke role privileges
GRANT TRC_CAPTURA_BASICA_ROLE TO &&newuser ;
GRANT TRC_CAPTURA_COMERCIAL_ROLE TO &&newuser;
GRANT TRC_CAPTURA_CONTACTOS_ROLE  TO &&newuser;

GRANT TRC_DISCOVERER  TO &&newuser;
GRANT TRC_DSI  TO &&newuser;
GRANT TRC_GESTIONES  TO &&newuser;
GRANT TRC_GEST_VENTANILLA  TO &&newuser;



REVOKE TRC_CAPTURA_CONTACTOS_COPIA FROM VVARGASN;

GRANT CM_ELAB_COMPROBANTE TO VVARGASN;
GRANT CM_RECIBO TO VVARGASN;
GRANT CO_CORREGIR_CATALOGOS TO VVARGASN;
GRANT CO_CREA_PROVEEDOR TO VVARGASN;
GRANT CO_DATA_PROVEEDOR TO VVARGASN;
GRANT CO_SOLO_CATALOGOS TO VVARGASN;
GRANT CO_TRAMITE_PAGO TO VVARGASN;
GRANT CO_SOLO_CATALOGOS TO VVARGASN;
GRANT PR_INFORMES_FUENTES TO VVARGASN;
GRANT PR_OPGET TO VVARGASN;
GRANT PR_TESORERIA TO VVARGASN;
GRANT RH_CONSULTA TO VVARGASN;

REVOKE CM_ELAB_COMPROBANTE FROM VVARGASN;
REVOKE CM_RECIBO FROM VVARGASN;
REVOKE CO_CORREGIR_CATALOGOS FROM VVARGASN;
REVOKE CO_CREA_PROVEEDOR FROM VVARGASN;
REVOKE CO_DATA_PROVEEDOR FROM VVARGASN;
REVOKE CO_SOLO_CATALOGOS FROM VVARGASN;
REVOKE CO_TRAMITE_PAGO FROM VVARGASN;
REVOKE CO_SOLO_CATALOGOS FROM VVARGASN;
REVOKE PR_INFORMES_FUENTES FROM VVARGASN;
REVOKE PR_OPGET FROM VVARGASN;
REVOKE PR_TESORERIA FROM VVARGASN;
REVOKE RH_CONSULTA FROM VVARGASN;

--AFORTEGON ANDRES ORTEGON
SELECT *
FROM USUARIOS_COMPANIA
WHERE USUARIO IN ('VVARGASN','AFORTEGON')

INSERT INTO USUARIOS_COMPANIA 
SELECT 'VVARGASN', CODIGO_COMPANIA, PERMITIR_MODIFICAR, SISTEMA, CODIGO_UNIDAD_EJECUTORA
FROM USUARIOS_COMPANIA
WHERE USUARIO = 'AFORTEGON'

--COMMIT;


select *
  from bintablas bb
 where bb.grupo = 'TERCEROS' 
 and  bb.nombre = 'FUNCIONARIO_TER'
 ;