select * --vigencia, entidad, unidad_ejecutora ue, consecutivo numero, estado, acta_de_recibo, nombre_interventor, detalle
from  ogt_orden_pago
where entidad=206
and consecutivo = 650 --472
and vigencia = 2007 --2025
and unidad_ejecutora='01' --'02'
;

select ogt_informacion_exogena.*
from ogt_registro_presupuestal , ogt_orden_pago, OGT_INFORMACION_EXOGENA
where 
--relación orden_pago y registro_presupuestal
OGT_REGISTRO_PRESUPUESTAL.VIGENCIA = OGT_ORDEN_PAGO.VIGENCIA AND 
OGT_REGISTRO_PRESUPUESTAL.ENTIDAD = OGT_ORDEN_PAGO.ENTIDAD AND 
OGT_REGISTRO_PRESUPUESTAL.UNIDAD_EJECUTORA = OGT_ORDEN_PAGO.UNIDAD_EJECUTORA AND 
OGT_REGISTRO_PRESUPUESTAL.TIPO_DOCUMENTO = OGT_ORDEN_PAGO.TIPO_DOCUMENTO AND 
OGT_REGISTRO_PRESUPUESTAL.CONSECUTIVO = OGT_ORDEN_PAGO.CONSECUTIVO AND
--relación registro_presupuestal e información exogena
OGT_INFORMACION_EXOGENA.VIGENCIA = OGT_REGISTRO_PRESUPUESTAL.VIGENCIA AND 
OGT_INFORMACION_EXOGENA.ENTIDAD = OGT_REGISTRO_PRESUPUESTAL.ENTIDAD AND 
OGT_INFORMACION_EXOGENA.UNIDAD_EJECUTORA = OGT_REGISTRO_PRESUPUESTAL.UNIDAD_EJECUTORA AND 
OGT_INFORMACION_EXOGENA.TIPO_DOCUMENTO  = OGT_REGISTRO_PRESUPUESTAL.TIPO_DOCUMENTO AND 
OGT_INFORMACION_EXOGENA.CONSECUTIVO  = OGT_REGISTRO_PRESUPUESTAL.CONSECUTIVO AND 
OGT_INFORMACION_EXOGENA.RUBRO_INTERNO = OGT_REGISTRO_PRESUPUESTAL.RUBRO_INTERNO AND 
OGT_INFORMACION_EXOGENA.VIGENCIA_PRESUPUESTO = OGT_REGISTRO_PRESUPUESTAL.VIGENCIA_PRESUPUESTO AND  
OGT_INFORMACION_EXOGENA.DISPONIBILIDAD = OGT_REGISTRO_PRESUPUESTAL.DISPONIBILIDAD AND 
OGT_INFORMACION_EXOGENA.REGISTRO = OGT_REGISTRO_PRESUPUESTAL.REGISTRO AND
--datos consulta ogt_orden_pago
ogt_orden_pago.entidad=206 and 
ogt_orden_pago.CONSECUTIVO=472 and --650 and 
ogt_orden_pago.vigencia=2025 and --207 and 
ogt_orden_pago.unidad_ejecutora='02';

s




