--connectado como OGT
grant ogt_admin to sl;

SELECT * FROM ALL_USERS
WHERE USERNAME IN ('DVEGA')
;

SELECT * FROM DBA_ROLES
WHERE ROLE LIKE 'RH%'
;

SELECT * FROM DBA_SYS_PRIVS
WHERE GRANTEE IN ('MBALLEN','')
ORDER BY 1,2
;


SELECT GRANTED_ROLE FROM DBA_ROLE_PRIVS
WHERE GRANTEE = 'MBALLEN'
;

SELECT * FROM ALL_TAB_PRIVS
WHERE TABLE_NAME = 'OGT_PK_INGRESO' --'PK_SIT_INFENTIDADES'
--WHERE GRANTEE = 'NEACOSTA';

CREATE PUBLIC SYNONYM PK_SIT_INFENTIDADES FOR SHD.PK_SIT_INFENTIDADES

SELECT owner, object_name, object_type
        FROM all_objects
        WHERE object_name = 'PK_SIT_INFENTIDADES';

select *
from alm_dtlle_ingreso        

GRANT INSERT ON OGT.OGT_DOCUMENTO TO PORTALP;