insert into ogt_concepto_tesoreria (
   id,
   concepto_hoja,
   descripcion,
   afecta_ingreso,
   afecta_egreso,
   afecta_pac,
   interno_rubro,
   id_rubro_equivalente,
   cote_id,
   fecha_inicial,
   fecha_final,
   compania,
   cabeza,
   cote_id_egreso
) values ( '00-02-37-17-00-00-00',
           1,
           'RECAUDO CAPITAL CUOTAS PARTES POR APLICAR FIDUDAVIVIENDA',
           2,
           5,
           0,
           - 1,
           null,
           '00-02-37-00-00-00-00',
           to_date('01-12-2024','dd-mm-yyyy'),
           null,
           '',
           '1',
           '' );

insert into ogt_concepto_tesoreria (
   id,
   concepto_hoja,
   descripcion,
   afecta_ingreso,
   afecta_egreso,
   afecta_pac,
   interno_rubro,
   id_rubro_equivalente,
   cote_id,
   fecha_inicial,
   fecha_final,
   compania,
   cabeza,
   cote_id_egreso
) values ( '00-02-37-18-00-00-00',
           1,
           'RECAUDO INTERESES CUOTAS PARTES POR APLICAR FIDUDAVIVIENDA',
           2,
           5,
           0,
           - 1,
           null,
           '00-02-37-00-00-00-00',
           to_date('01-12-2024','dd-mm-yyyy'),
           null,
           '',
           '1',
           '' );