CREATE OR REPLACE PACKAGE "OGT".PK_OGT_BD_CREAR_RA IS

  -- DEFINIR CADA FILA DE LA TABLA OGT_RELACION_AUTORIZACION
  TYPE RAREC IS RECORD
    (MI_TIPO_DOCUMENTO        OGT_RELACION_AUTORIZACION.TIPO_DOCUMENTO%TYPE
    ,MI_ENTIDAD               OGT_RELACION_AUTORIZACION.ENTIDAD%TYPE
    ,MI_UNIDAD_EJECUTORA      OGT_RELACION_AUTORIZACION.UNIDAD_EJECUTORA%TYPE
    ,MI_VIGENCIA              OGT_RELACION_AUTORIZACION.VIGENCIA%TYPE
    ,MI_CONSECUTIVO           OGT_RELACION_AUTORIZACION.CONSECUTIVO%TYPE
    ,MI_TIPO_RA               OGT_RELACION_AUTORIZACION.TIPO_RA%TYPE
    ,MI_MES                   OGT_RELACION_AUTORIZACION.MES%TYPE
    ,MI_FECHA_DESDE           OGT_RELACION_AUTORIZACION.FECHA_DESDE%TYPE
    ,MI_FECHA_HASTA           OGT_RELACION_AUTORIZACION.FECHA_HASTA%TYPE
    ,MI_ESTADO                OGT_RELACION_AUTORIZACION.ESTADO%TYPE
    ,MI_FECHA_RADICACION      OGT_RELACION_AUTORIZACION.FECHA_RADICACION%TYPE
    ,MI_FIRMA_ORDENADOR       OGT_RELACION_AUTORIZACION.FIRMA_ORDENADOR%TYPE
    ,MI_USUARIO_RADICA        OGT_RELACION_AUTORIZACION.USUARIO_RADICA%TYPE
    ,MI_DESCRIPCION           OGT_RELACION_AUTORIZACION.DESCRIPCION%TYPE
    ,MI_NUMERO_COMPROMISO     OGT_RELACION_AUTORIZACION.NUMERO_COMPROMISO%TYPE
    ,MI_FECHA_DILIGENCIAMIENTO OGT_DOCUMENTO_PAGO.FECHA_DILIGENCIAMIENTO%TYPE
    ,MI_USUARIO_ELABORO       OGT_DOCUMENTO_PAGO.USUARIO_ELABORO%TYPE
    ,MI_USUARIO_REVISO        OGT_DOCUMENTO_PAGO.USUARIO_REVISO%TYPE
    ,MI_SITUACION_FONDOS      OGT_RELACION_AUTORIZACION.SITUACION_FONDOS%TYPE --S/N
    );

  -- VARIABLE TIPO RAREC
  MI_RAREC   RAREC;

  -- DEFINIR CADA FILA DE LA TABLA OGT_IMPUTACION
  TYPE IMPREC IS RECORD
    (MI_RUBRO_INTERNO                OGT_IMPUTACION.RUBRO_INTERNO%TYPE
    ,MI_DISPONIBILIDAD               OGT_IMPUTACION.DISPONIBILIDAD%TYPE
    ,MI_VALOR_BRUTO                  OGT_IMPUTACION.VALOR_BRUTO%TYPE
    ,MI_ANO_PAC                      OGT_IMPUTACION.ANO_PAC%TYPE
    ,MI_MES_PAC                      OGT_IMPUTACION.MES_PAC%TYPE
    ,MI_REGISTRO                     OGT_REGISTRO_PRESUPUESTAL.REGISTRO%TYPE
    ,MI_VALOR_REGISTRO               OGT_REGISTRO_PRESUPUESTAL.VALOR_REGISTRO%TYPE
    );

  -- DEFINIR LA TABLA DE REGISTROS
  TYPE IMPTAB IS TABLE OF IMPREC INDEX BY BINARY_INTEGER;

  -- INI 2025002524 
  -- RQ1786-2006  13/10/2006
  -- DEFINIR CADA FILA DE LA TABLA OGT_FUENTES_FINANCIACION
  TYPE FTEREC IS RECORD(
    MI_RUBRO_INTERNO      OGT_IMPUTACION.RUBRO_INTERNO%TYPE,
    MI_DISPONIBILIDAD     OGT_IMPUTACION.DISPONIBILIDAD%TYPE,
    MI_REGISTRO           OGT_REGISTRO_PRESUPUESTAL.REGISTRO%TYPE,
    MI_CODIGO_FUENTE      OGT_RP_FUENTES.CODIGO_FUENTE%TYPE,
    MI_CONSECUTIVO_FUENTE OGT_RP_FUENTES.CONSECUTIVO_FUENTE%TYPE,
    MI_VALOR              OGT_RP_FUENTES.VALOR%TYPE);

  -- DEFINIR LA TABLA DE REGISTROS
  TYPE FTETAB IS TABLE OF FTEREC INDEX BY BINARY_INTEGER;
  -- FIN RQ1786-2006
  -- FIN 2025002524 


  -- DEFINIR CADA FILA DE LA TABLA OGT_CENTRO_COSTOS
  TYPE CC_RA_REC IS RECORD
    (MI_CODIGO_CENTRO_COSTOS    OGT_CENTRO_COSTOS.CODIGO_CENTRO_COSTOS%TYPE
    ,MI_AUTORIZADO              OGT_CENTRO_COSTOS.AUTORIZADO%TYPE
    ,MI_VALOR                   OGT_CENTRO_COSTOS.VALOR%TYPE
    ,MI_CUENTA_CONTABLE_ENTIDAD OGT_CENTRO_COSTOS.CUENTA_CONTABLE_ENTIDAD%TYPE
    );

  -- DEFINIR LA TABLA DE REGISTROS
  TYPE CCTAB IS TABLE OF CC_RA_REC INDEX BY BINARY_INTEGER;

  -- DEFINIR CADA FILA DE LA TABLA  OGT_ANEXO_NOMINA
  TYPE ANREC IS RECORD
    (MI_TIPO_PAGAR_A           VARCHAR2(30)   -- TIPO DOCUMENTO
    ,MI_NRO_PAGAR_A            VARCHAR2(20)   -- NUMERO DOCUMENTO
    ,MI_NUMERO_CUENTA          VARCHAR2(30)
    ,MI_SUCURSAL               VARCHAR2(30)
    ,MI_BANCO                  VARCHAR2(20)
    ,MI_TIPO_CUENTA            VARCHAR2(30)
    ,MI_APORTE_EMPLEADO        VARCHAR2(20)
    ,MI_FORMA_PAGO             VARCHAR2(15)
    ,MI_CODIGO_CENTRO_COSTOS   VARCHAR2(4)
    );

  -- DEFINIR LA TABLA DE REGISTROS
  TYPE ANTAB IS TABLE OF ANREC INDEX BY BINARY_INTEGER;

  -- DEFINIR CADA FILA DE LA TABLA  OGT_ANEXO_EMBARGO
  TYPE AEREC IS RECORD
    (MI_TIPO_PAGAR_A           VARCHAR2(30)   -- TIPO DOCUMENTO
    ,MI_NRO_PAGAR_A            VARCHAR2(20)   -- NUMERO DOCUMENTO
    --INI 2025002524 
    --RQ1294-2005              05/06/2006
    ,MI_TIPO_JUZGADO          VARCHAR2(30)    -- TIPO DOCUMENTO
    ,MI_NRO_JUZGADO           VARCHAR2(20)    -- NUMERO DOCUMENTO
    --Fin RQ1294-2005
    --FIN 2025002524 
    ,MI_TIPO_ID                VARCHAR2(30)   -- TIPO DOCUMENTO
    ,MI_NRO_ID                 VARCHAR2(20)   -- NUMERO DOCUMENTO
    ,MI_TIPO_ID_EMBARGADO      VARCHAR2(30)   -- TIPO DOCUMENTO
    ,MI_NRO_ID_EMBARGADO       VARCHAR2(20)   -- NUMERO DOCUMENTO
    ,MI_NUMERO_OFICIO          VARCHAR2(15)
    ,MI_OFICINA_ORIGEN         VARCHAR2(20)
    ,MI_OFICINA_DESTINO        VARCHAR2(20)
    ,MI_APORTE_EMBARGO         VARCHAR2(20)
    ,MI_FORMA_PAGO             VARCHAR2(15)
    ,MI_FUERA_CIUDAD           VARCHAR2(1)
    ,MI_NUMERO_CUENTA          VARCHAR2(30)
    ,MI_SUCURSAL               VARCHAR2(30)
    ,MI_BANCO                  VARCHAR2(20)
    ,MI_TIPO_CUENTA   VARCHAR2(30)
    ,MI_CONCEPTO    VARCHAR2(30)
    ,MI_NOMBRE_EMBARGANTE      VARCHAR2(200)
    ,MI_CODIGO_CENTRO_COSTOS   VARCHAR2(4)
    );

  -- DEFINIR LA TABLA DE REGISTROS
  TYPE AETAB IS TABLE OF AEREC INDEX BY BINARY_INTEGER;

  -- DEFINIR CADA FILA DE LA TABLA  OGT_ANEXO_PATRONAL
  TYPE APREC IS RECORD
    (MI_TIPO_PAGAR_A           VARCHAR2(30)   -- TIPO DOCUMENTO
    ,MI_NRO_PAGAR_A            VARCHAR2(20)   -- NUMERO DOCUMENTO
    ,MI_TIPO_ID                VARCHAR2(30)   -- TIPO DOCUMENTO
    ,MI_NRO_ID                 VARCHAR2(20)   -- NUMERO DOCUMENTO
    ,MI_APORTE_PATRONAL         VARCHAR2(20)
    ,MI_APORTE_EMPLEADO         VARCHAR2(20)
    ,MI_FORMA_PAGO              VARCHAR2(15)
    ,MI_SALDO                   VARCHAR2(20)
    ,MI_INCAPACIDAD             VARCHAR2(20)
    ,MI_NUMERO_CUENTA           VARCHAR2(30)
    ,MI_SUCURSAL                VARCHAR2(30)
    ,MI_BANCO                   VARCHAR2(20)
    ,MI_TIPO_CUENTA             VARCHAR2(30)
    ,MI_CODIGO_CENTRO_COSTOS    VARCHAR2(4)
    );

  -- DEFINIR LA TABLA DE REGISTROS
  TYPE APTAB IS TABLE OF APREC INDEX BY BINARY_INTEGER;

  -- DEFINE LOS REGISTROS DE IMPUTACION DE UNA RA
  TYPE CUR_IMPUTACION          IS REF CURSOR;

  -- DEFINE LOS REGISTROS DEL CC DE UNA RA
  TYPE CUR_CC          IS REF CURSOR;

  -- DEFINE EL TIPO DE REGISTRO DEL LA TABLA HASH
  TYPE HASHREC IS RECORD
    (MI_CADENA_HASH   LONG
    );

  -- DEFINIR LA TABLA DE CADENAS HASH
  TYPE HASHTAB IS TABLE OF HASHREC INDEX BY BINARY_INTEGER;

  -- DEFINE LA TABLA DE CDENAS HASH
  UN_TAB_LONG HASHTAB;

  -- REGISTRO DE CENTROS DE COSTOS DE RA
   TYPE CCREG IS RECORD
    (MI_CODIGO_CENTRO_COSTOS      OGT_CONCEPTO_RA.CODIGO_CENTRO_COSTOS%TYPE
    ,MI_NOMBRE_CENTRO_COSTOS      OGT_CONCEPTO_RA.NOMBRE_CENTRO_COSTOS%TYPE
    ,MI_CUENTA_CONTABLE           OGT_CONCEPTO_RA.CUENTA_CONTABLE%TYPE
    ,MI_TIPO_ANEXO                OGT_CONCEPTO_RA.TIPO_ANEXO%TYPE
    ,MI_ID                        OGT_CONCEPTO_RA.ID%TYPE
    ,MI_ENTIDAD                   OGT_CONCEPTO_RA.ENTIDAD%TYPE
    ,MI_AFECTA_RETENCION          OGT_CONCEPTO_RA.AFECTA_RETENCION%TYPE
    ,MI_AFECTA_EMBARGOS           OGT_CONCEPTO_RA.AFECTA_EMBARGOS%TYPE
    ,MI_NETO_NOMINA               OGT_CONCEPTO_RA.NETO_NOMINA%TYPE
    ,MI_VALIDAR_SALDO             OGT_CONCEPTO_RA.VALIDAR_SALDO%TYPE
    );

  -- CURSOR DE  CENTROS DE COSTOS DE RA
  TYPE CUR_CCREG IS REF CURSOR RETURN CCREG;

  TYPE REG_INFCOMERCIAL_PRO IS RECORD
  (MI_BANCO       OGT_RA_FORMA_PAGO.BANCO%TYPE
  ,MI_TIPO_CUENTA    OGT_RA_FORMA_PAGO.TIPO_CUENTA%TYPE
  ,MI_NUMERO_CUENTA   OGT_RA_FORMA_PAGO.NUMERO_CUENTA%TYPE
  ,MI_FORMA_PAGO    OGT_RA_FORMA_PAGO.FORMA_PAGO%TYPE
  );

  TYPE REG_INFBASICA_PRO IS RECORD
  (MI_ID        OGT_PROVEEDORES_RA.ID%TYPE
  ,MI_PRIMER_NOMBRE     VARCHAR2(120)
  ,MI_SEGUNDO_NOMBRE    VARCHAR2(120)
  ,MI_PRIMER_APELLIDO   VARCHAR2(120)
  ,MI_SEGUNDO_APELLIDO  VARCHAR2(120)
  ,MI_FUNCIONARIO       OGT_PROVEEDORES_RA.FUNCIONARIO%TYPE
  );

  TYPE REG_PROVEEDORES IS RECORD
  (MI_ID   OGT_PROVEEDORES_RA.ID%TYPE
  ,MI_NOMBRE             VARCHAR2(500)
  ,MI_TIPO_IDENTIFICACION     OGT_PROVEEDORES_RA.TIPO_IDENTIFICACION%TYPE
  ,MI_CODIGO_IDENTIFICACION   OGT_PROVEEDORES_RA.CODIGO_IDENTIFICACION%TYPE
  ,MI_BANCO   OGT_RA_FORMA_PAGO.BANCO%TYPE
  ,MI_TIPO_CUENTA  OGT_RA_FORMA_PAGO.TIPO_CUENTA%TYPE
  ,MI_NUMERO_CUENTA  OGT_RA_FORMA_PAGO.NUMERO_CUENTA%TYPE
  ,MI_FORMA_PAGO  OGT_RA_FORMA_PAGO.FORMA_PAGO%TYPE
  ,MI_FUNCIONARIO         OGT_PROVEEDORES_RA.FUNCIONARIO%TYPE
  ,MI_FECHA_INICIAL  OGT_RA_FORMA_PAGO.FECHA_INICIAL%TYPE
  ,MI_FECHA_FINAL  OGT_RA_FORMA_PAGO.FECHA_FINAL%TYPE
  );

  TYPE REG_PAGO_CAUSADO IS RECORD
  (MI_ENTIDAD             OGT_DETALLE_EGRESO.ENTIDAD%TYPE
  ,MI_FECHA_PAGO  DATE
  ,MI_VALOR               OGT_DETALLE_PAGO.VALOR%TYPE
  );

  -- DEFINIR LA TABLA DE REGISTROS DE PAGOS CAUSADOS
  TYPE PPCTAB IS TABLE OF REG_PAGO_CAUSADO INDEX BY BINARY_INTEGER;

  -- DEFINIR TIPO DE REGISTRO PARA TABLA PL DE ERRORES DEL CARGUE DE ANEXOS
  TYPE REC_ERROR IS RECORD
  (MI_LINEA                VARCHAR2(200)
  ,MI_CODIGO               NUMBER
  );

  -- DEFINIR TABLA PL DE REGISTRO DE ERRORES
  TYPE ERTAB IS TABLE OF REC_ERROR INDEX BY BINARY_INTEGER;

  -- TIPO DE REGISTRO PARA RA GIRADAS CON INF PRESUPUESTAL

  TYPE REG_IMPUTACION_GIRADAS IS RECORD (
 MI_FECHA_GIRO_PRESUPUESTAL  OGT_REGISTRO_PRESUPUESTAL.FECHA_GIRO_PRESUPUESTAL%TYPE,
 MI_USUARIO_GIRO_PRESUPUESTAL  OGT_REGISTRO_PRESUPUESTAL.USUARIO_GIRO_PRESUPUESTAL%TYPE,
 MI_ID_LIMAY_PAGO    OGT_REGISTRO_PRESUPUESTAL.ID_LIMAY_PAGO%TYPE,
 MI_FECHA_PAGO    OGT_REGISTRO_PRESUPUESTAL.FECHA_PAGO%TYPE,
 MI_USUARIO_PAGO    OGT_REGISTRO_PRESUPUESTAL.USUARIO_PAGO%TYPE,
 MI_RUBRO_INTERNO    OGT_REGISTRO_PRESUPUESTAL.RUBRO_INTERNO%TYPE,
 MI_UNIDAD_EJECUTORA_PRE  OGT_REGISTRO_PRESUPUESTAL.UNIDAD_EJECUTORA_PRESUPUESTO%TYPE,
 MI_DISPONIBILIDAD   OGT_REGISTRO_PRESUPUESTAL.DISPONIBILIDAD%TYPE,
 MI_VIGENCIA_PRESUPUESTO  OGT_REGISTRO_PRESUPUESTAL.VIGENCIA_PRESUPUESTO%TYPE,
 MI_TIPO_DOCUMENTO   OGT_REGISTRO_PRESUPUESTAL.TIPO_DOCUMENTO%TYPE,
 MI_UNIDAD_EJECUTORA   OGT_REGISTRO_PRESUPUESTAL.UNIDAD_EJECUTORA%TYPE,
 MI_ENTIDAD     OGT_REGISTRO_PRESUPUESTAL.ENTIDAD%TYPE,
 MI_VIGENCIA    OGT_REGISTRO_PRESUPUESTAL.VIGENCIA%TYPE,
 MI_CONSECUTIVO    OGT_REGISTRO_PRESUPUESTAL.CONSECUTIVO%TYPE,
 MI_ENTIDAD_PRESUPUESTO   OGT_REGISTRO_PRESUPUESTAL.ENTIDAD_PRESUPUESTO%TYPE,
 MI_REGISTRO    OGT_REGISTRO_PRESUPUESTAL.REGISTRO%TYPE,
 MI_VALOR_REGISTRO   OGT_REGISTRO_PRESUPUESTAL.VALOR_REGISTRO%TYPE);

  -- CURSOR DE REGISTROS PARA RA GIRADAS CON INF PRESUPUESTAL

  TYPE CUR_IMPUTACION_GIRADAS IS REF CURSOR RETURN REG_IMPUTACION_GIRADAS;

  /***************************************************************************/
  -- DEFINE EL PROCEDIMIENTO PARA CREACION DE RA
  -- RECIBE UN REGISTTRO CON LA INFORMACION NECESARIA
  -- RETORNA UN CODIGO QUE INDICA EL ESTADO DE LA CREACION
  /***************************************************************************/
  PROCEDURE PR_CREA_RA(UN_REG_RA            IN     RAREC
                      ,UN_CODIGO            IN OUT NUMBER
                      ,UNA_TABLA_IMPUTACION IN     IMPTAB
                      ,UNA_TABLA_CENTRO     IN     CCTAB
                      ,UNA_TABLA_NOMINA     IN     ANTAB
                      ,UNA_TABLA_EMBARGO    IN     AETAB
                      ,UNA_TABLA_APORTES    IN     APTAB
       ,UN_CONSECUTIVO       IN OUT OGT_RELACION_AUTORIZACION.CONSECUTIVO%TYPE
       ,UN_PL_ERR            IN OUT ERTAB   -- LISTA DE ERRORES
                      );

  /***************************************************************************/
  -- DEFINE EL PROCEDIMIENTO PARA CREACION DE LA IMPUTACION
  /***************************************************************************/
  PROCEDURE PR_CREA_IMPUTACION (UN_REG_RA      IN     RAREC
      ,UNA_TABLA_IMP  IN     IMPTAB
      ,UN_CONSECUTIVO IN VARCHAR2
      ,UN_CODIGO      IN OUT NUMBER
           ,UN_PL_ERR    IN OUT ERTAB   -- LISTA DE ERRORES
           ,UN_ABORTE    IN OUT VARCHAR2 -- INDICA SI HAY POR LO MENOS UN ERROR QUE NO PERMITE CARGUE '1'
           ,UN_I         IN OUT NUMBER   -- CONTADOR DE LA TABLA PL
        );

  /***************************************************************************/
  -- DEFINE EL PROCEDIMIENTO PARA CREACION DE CC
  -- RECIBE UNA TABLA PL CON LA INFORMACION PARA CREAR LA CREACION
  -- RETORNA UN CODIGO QUE INDICA EL ESTADO DE LA CREACION
  /***************************************************************************/
  PROCEDURE PR_CREA_CC (UN_REG_RA      IN RAREC
        ,UNA_TABLA_CC      CCTAB
        ,UN_CONSECUTIVO IN VARCHAR2
                       ,UN_CODIGO      IN OUT NUMBER
        ,UN_PL_ERR    IN OUT ERTAB   -- LISTA DE ERRORES
        ,UN_ABORTE    IN OUT VARCHAR2 -- INDICA SI HAY POR LO MENOS UN ERROR QUE NO PERMITE CARGUE '1'
        ,UN_I         IN OUT NUMBER   -- CONTADOR DE LA TABLA PL
                       );

  /***************************************************************************/
  -- DEFINE EL PROCEDIMIENTO PARA CREACION DE AN
  -- RECIBE UNA TABLA PL CON LA INFORMACION PARA CREAR LA CREACION
  -- RETORNA UN CODIGO QUE INDICA EL ESTADO DE LA CREACION
  /***************************************************************************/
  PROCEDURE PR_CREA_AN(UN_REG_RA    IN RAREC
       ,UNA_TABLA_AN IN ANTAB
       ,UN_CONSECUTIVO IN VARCHAR2
                      ,UN_CODIGO    IN OUT NUMBER
       ,UN_PL_ERR    IN OUT ERTAB   -- LISTA DE ERRORES
       ,UN_ABORTE    IN OUT VARCHAR2 -- INDICA SI HAY POR LO MENOS UN ERROR QUE NO PERMITE CARGUE '1'
       ,UN_I         IN OUT NUMBER   -- CONTADOR DE LA TABLA PL
    );

  /***************************************************************************/
  -- DEFINE EL PROCEDIMIENTO PARA CREACION DE AP
  -- RECIBE UNA TABLA PL CON LA INFORMACION PARA CREAR LA CREACION
  -- RETORNA UN CODIGO QUE INDICA EL ESTADO DE LA CREACION
  /***************************************************************************/
  PROCEDURE PR_CREA_AP(UN_REG_RA    IN RAREC
       ,UNA_TABLA_AP IN APTAB
       ,UN_CONSECUTIVO IN VARCHAR2
                      ,UN_CODIGO    IN OUT NUMBER
       ,UN_PL_ERR    IN OUT ERTAB   -- LISTA DE ERRORES
       ,UN_ABORTE    IN OUT VARCHAR2 -- INDICA SI HAY POR LO MENOS UN ERROR QUE NO PERMITE CARGUE '1'
       ,UN_I         IN OUT NUMBER   -- CONTADOR DE LA TABLA PL
    ) ;

  /***************************************************************************/
  -- DEFINE EL PROCEDIMIENTO PARA CREACION DE AE
  -- RECIBE UNA TABLA PL CON LA INFORMACION PARA CREAR LA CREACION
  -- RETORNA UN CODIGO QUE INDICA EL ESTADO DE LA CREACION
  /***************************************************************************/
  PROCEDURE PR_CREA_AE(UN_REG_RA    IN RAREC
       ,UNA_TABLA_AE IN AETAB
       ,UN_CONSECUTIVO IN VARCHAR2
                      ,UN_CODIGO    IN OUT NUMBER
       ,UN_PL_ERR    IN OUT ERTAB   -- LISTA DE ERRORES
       ,UN_ABORTE    IN OUT VARCHAR2 -- INDICA SI HAY POR LO MENOS UN ERROR QUE NO PERMITE CARGUE '1'
       ,UN_I         IN OUT NUMBER   -- CONTADOR DE LA TABLA PL
    ) ;

  /***************************************************************************/
  -- DEFINE EL PROCEDIMIENTO PARA MODIFICAR UNA POSICION DEL ARREGLO DEL
  -- ESTADO DE LA RA
  /***************************************************************************/
   PROCEDURE PR_CAMBIA_POSICION_ESTADO(UNA_POSICION   NUMBER
          ,UN_VALOR       NUMBER
           ,UN_RETORNO     IN OUT OGT_RELACION_AUTORIZACION.ESTADO%TYPE);

  /***************************************************************************/
  -- DEFINE EL PROCEDIMIENTO PARA VERIFICAR EL ESTADO DE UNA RA
  /***************************************************************************/
 PROCEDURE PR_VERIFICA_ESTADO(UNA_TABLA           VARCHAR2
        ,UN_ESTADO           OGT_RELACION_AUTORIZACION.ESTADO%TYPE
      ,UN_RETORNO          IN OUT VARCHAR2
      );

  /***************************************************************************/
  -- OBJETIVO:   ENCABEZADO DE UNA RA PARA LA GENERACION DEL REPORTE DE RA
  -- IMPUTACION
  -- EL INFORME SE PODRA GENERAR PARA CUALQUIER RA INDEPENDIENTEMENTE DE SU ESTADO
  -- PARAMETROS: VIGENCIA, ENTIDAD, UNIDAD, TIPO_DOCUMENTO, CONSECUTIVO
  /***************************************************************************/
  FUNCTION OGT_FN_ENCABEZADO_RA(UN_VIGENCIA         OGT_RELACION_AUTORIZACION.VIGENCIA%TYPE
                   ,UN_ENTIDAD          OGT_RELACION_AUTORIZACION.ENTIDAD%TYPE
                      ,UN_UNIDAD_EJECUTORA OGT_RELACION_AUTORIZACION.UNIDAD_EJECUTORA%TYPE
                        ,UN_TIPO_DOCUMENTO   OGT_RELACION_AUTORIZACION.TIPO_DOCUMENTO%TYPE
                       ,UN_CONSECUTIVO      OGT_RELACION_AUTORIZACION.CONSECUTIVO%TYPE
                         ) RETURN RAREC;

  /***************************************************************************/
  -- OBJETIVO:   CUERPO DEL REPORTE DE RA IMPUTACION
  -- EL INFORME SE PODRA GENERAR PARA CUALQUIER RA INDEPENDIENTEMENTE DE SU ESTADO
  -- PARAMETROS: VIGENCIA, ENTIDAD, UNIDAD, TIPO_DOCUMENTO, CONSECUTIVO
  /***************************************************************************/
  FUNCTION OGT_FN_CUERPO_RA(UN_VIGENCIA  OGT_RELACION_AUTORIZACION.VIGENCIA%TYPE
                             ,UN_ENTIDAD          OGT_RELACION_AUTORIZACION.ENTIDAD%TYPE
                               ,UN_UNIDAD_EJECUTORA OGT_RELACION_AUTORIZACION.UNIDAD_EJECUTORA%TYPE
                                 ,UN_TIPO_DOCUMENTO   OGT_RELACION_AUTORIZACION.TIPO_DOCUMENTO%TYPE
                             ,UN_CONSECUTIVO      OGT_RELACION_AUTORIZACION.CONSECUTIVO%TYPE
                             ) RETURN CUR_IMPUTACION;

  /***************************************************************************/
  -- OBJETIVO:   RESUMEN DE CENTRO DE COSTOS PARA UNA RA
  -- EL INFORME SE PODRA GENERAR PARA CUALQUIER RA INDEPENDIENTEMENTE DE SU ESTADO
  -- PARAMETROS: VIGENCIA, ENTIDAD, UNIDAD, TIPO_DOCUMENTO, CONSECUTIVO
  /***************************************************************************/
  FUNCTION OGT_FN_CC_RA(UN_VIGENCIA         OGT_RELACION_AUTORIZACION.VIGENCIA%TYPE
               ,UN_ENTIDAD          OGT_RELACION_AUTORIZACION.ENTIDAD%TYPE
                 ,UN_UNIDAD_EJECUTORA OGT_RELACION_AUTORIZACION.UNIDAD_EJECUTORA%TYPE
                   ,UN_TIPO_DOCUMENTO   OGT_RELACION_AUTORIZACION.TIPO_DOCUMENTO%TYPE
                  ,UN_CONSECUTIVO      OGT_RELACION_AUTORIZACION.CONSECUTIVO%TYPE
                  ,UN_FECHA_DESDE   OGT_RELACION_AUTORIZACION.FECHA_DESDE%TYPE
                  ,UN_TIPO_RA    OGT_RELACION_AUTORIZACION.TIPO_RA%TYPE
                  ,UN_MES      OGT_RELACION_AUTORIZACION.MES%TYPE
                   ) RETURN CUR_CC;

  /***************************************************************************/
  -- OBJETIVO:   GENERAR EL HASH PARA RA
  -- SE PODRA GENERAR INPENDIENTEMENTE DEL ESTADO DE LA RA
  -- PARAMETROS: VIGENCIA, ENTIDAD, UNIDAD, TIPO_DOCUMENTO, CONSECUTIVO
  /***************************************************************************/
  FUNCTION OGT_FN_CADENA_HASH_RA(UN_VIGENCIA         OGT_RELACION_AUTORIZACION.VIGENCIA%TYPE
                        ,UN_ENTIDAD          OGT_RELACION_AUTORIZACION.ENTIDAD%TYPE
                            ,UN_UNIDAD_EJECUTORA OGT_RELACION_AUTORIZACION.UNIDAD_EJECUTORA%TYPE
                            ,UN_TIPO_DOCUMENTO   OGT_RELACION_AUTORIZACION.TIPO_DOCUMENTO%TYPE
                           ,UN_CONSECUTIVO      OGT_RELACION_AUTORIZACION.CONSECUTIVO%TYPE
                             ) RETURN LONG;

  /***************************************************************************/
  -- OBJETIVO:   RETORNAR SI UN DETERMINADO CONCEPTO AFECTA EMBARGOS
  -- PARAMETROS: CODIGO_CENTRO_COSTOS
  /***************************************************************************/
     FUNCTION OGT_FN_CONCEPTO_EMBARGO  (UN_CC OGT_CENTRO_COSTOS.CODIGO_CENTRO_COSTOS%TYPE
      ) RETURN VARCHAR2;

  /***************************************************************************/
  -- DEFINE EL PROCEDIMIENTO QUE RETORNA UN CURSOR CON LA INFORMACION DE LOS
  -- CENTROS DE COSTOS REQUERIDA PARA CONTABILIZAR RA
  -- PARAMETROS:
  --  ENTIDAD
  -- RETORNO:
  --  CURSOR DE TIPO CUR_CCREG
  /***************************************************************************/
  FUNCTION OGT_FN_CONCEPTOS_RA(UNA_ENTIDAD          OGT_EGRESO.ENTIDAD%TYPE
                    ) RETURN CUR_CCREG;

/***************************************************************************/
  -- AUTOR:      FANNY MALAGON
  -- OBJETIVO:   CONSULTA Y RETORNA EL ID DEL PROVEEDOR
  -- PARAMETROS: TIPO DE DOCUMENTO
  --             NUMERO DE DOCUMENTO
  -- RETORNA INFORMACION BASICA DEL PROVEEDOR
  --   SI FUE EXITOSA RETORNA EL ID Y EL NOMBRE
  --   SI FUE FALLIDA RETORNA NULL
/***************************************************************************/

  FUNCTION FN_INFBASICA_PROVEEDOR(UN_TIPO_DOCUMENTO    OGT_PROVEEDORES_RA.TIPO_IDENTIFICACION%TYPE
     ,UN_NUMERO_DOCUMENTO  OGT_PROVEEDORES_RA.CODIGO_IDENTIFICACION%TYPE
     ) RETURN REG_INFBASICA_PRO;

/***************************************************************************/
  -- AUTOR:      FANNY MALAGON
  -- OBJETIVO:   CONSULTA Y RETORNA LA FORMA DE PAGO DE UN PROVEEDOR VIGENTE O A UNA FECHA
  -- PARAMETROS: TIPO DE DOCUMENTO
  --             NUMERO DE DOCUMENTO
  -- RETORNA FORMA DE PAGO
  --     NUMERO DE CUENTA
  --     TIPO DE CUENTA
  --         BANCO
  --   SI FUE EXITOSA RETORNA EL REGISTRO
  --   SI FUE FALLIDA RETORNA NULL
/***************************************************************************/

  FUNCTION FN_INFCOMERCIAL_PROVEEDOR(UN_TIPO_DOCUMENTO    OGT_PROVEEDORES_RA.TIPO_IDENTIFICACION%TYPE
              ,UN_NUMERO_DOCUMENTO  OGT_PROVEEDORES_RA.CODIGO_IDENTIFICACION%TYPE
              ,UNA_FECHA            DATE
     ) RETURN REG_INFCOMERCIAL_PRO;

/***************************************************************************/
  -- AUTOR:      FANNY MALAGON
  -- OBJETIVO:   CONSULTA Y RETORNA INFORMACION APARTIR DEL ID
  -- PARAMETROS: ID
  -- RETORNA INFORMACION BASICA
  --      FORMA DE PAGO
  --     NUMERO DE CUENTA
  --     TIPO DE CUENTA
  --         BANCO
  --   SI FUE EXITOSA RETORNA EL REGISTRO
  --   SI FUE FALLIDA RETORNA NULL
/***************************************************************************/

  FUNCTION FN_ID_PROVEEDOR(UN_ID    OGT_PROVEEDORES_RA.ID%TYPE
    ,UNA_FECHA DATE
    ) RETURN REG_PROVEEDORES;

/***************************************************************************/
  -- AUTOR:      FANNY MALAGON
  -- OBJETIVO:   EVALUA SI EXISTE UN PROVEEDOR DE RA
  -- PARAMETROS: ID
  -- RETORNA NUMBER
  --   EL ID HOMOLOGADO SI EXISTE
  --   EL MISMO ID SI NO ESTA HOMOLOGADO Y EXISTE
  --   CERO SI NO EXISTE Y NO ESTA HOMOLOGADO
/***************************************************************************/

  FUNCTION FN_EXISTE_PROVEEDOR(UN_ID    OGT_PROVEEDORES_RA.ID%TYPE
  --INI 2025002524 Se elimina, en version fonce no existe campo fecha
  --,una_fecha                           DATE DEFAULT SYSDATE
  --FIN 2025002524 
   ) RETURN NUMBER;

/***************************************************************************/
  -- AUTOR:      FANNY MALAGON
  -- OBJETIVO:   CREA UN PROVEEDOR DE RA
  -- RETORNA NUMBER
  --   0 SI CREO
  --   SQLERRM NO CREO
/***************************************************************************/

  FUNCTION FN_CREA_PROVEEDOR(UN_ID                OGT_PROVEEDORES_RA.ID%TYPE
    ,UN_TIPO_IDENTIFICACION   OGT_PROVEEDORES_RA.TIPO_IDENTIFICACION%TYPE
    ,UN_CODIGO_IDENTIFICACION OGT_PROVEEDORES_RA.CODIGO_IDENTIFICACION%TYPE
    ,UN_PRIMER_NOMBRE         OGT_PROVEEDORES_RA.PRIMER_NOMBRE%TYPE
    ,UN_SEGUNDO_NOMBRE        OGT_PROVEEDORES_RA.SEGUNDO_NOMBRE%TYPE
    ,UN_PRIMER_APELLIDO       OGT_PROVEEDORES_RA.PRIMER_APELLIDO%TYPE
    ,UN_SEGUNDO_APELLIDO      OGT_PROVEEDORES_RA.SEGUNDO_APELLIDO%TYPE
    ,UN_FORMA_PAGO            OGT_RA_FORMA_PAGO.FORMA_PAGO%TYPE
    ,UN_BANCO                 OGT_RA_FORMA_PAGO.BANCO%TYPE
    ,UN_TIPO_CUENTA           OGT_RA_FORMA_PAGO.TIPO_CUENTA%TYPE
    ,UN_NUMERO_CUENTA         OGT_RA_FORMA_PAGO.NUMERO_CUENTA%TYPE
   ) RETURN VARCHAR2;

/***************************************************************************/
  -- AUTOR:      FANNY MALAGON
  -- OBJETIVO:   RETORNA LOS PAGOS PARA UN CODIGO CONTABLE (RETENCION)
  --             PARA UN INTERVALO DE FECHAS
  -- RETORNA     TABLA PL (ENTIDAD, FECHA_PAGO, VALOR)
/***************************************************************************/

  FUNCTION FN_PAGOS_CAUSADOS
   (UN_CUENTA_CONTABLE       OGT_CONCEPTO_RA.CUENTA_CONTABLE%TYPE
   ,UN_FECHA_INICIAL    DATE
   ,UN_FECHA_FINAL    DATE
   ) RETURN  PPCTAB;

/***************************************************************************/
  -- AUTOR:      FANNY MALAGON
  -- OBJETIVO:   RETORNA EL ESTADO DE UN CENTRO DE COSTOS DE RA
  -- RETORNA     BOOLEAN
  --             TRUE   ACTIVO
  --             FALSE  INACTIVO
/***************************************************************************/

  FUNCTION FN_ESTADO_CC
   (UN_CODIGO_CENTRO_COSTOS     OGT_CONCEPTO_RA.CODIGO_CENTRO_COSTOS%TYPE
   ) RETURN  BOOLEAN;

/***************************************************************************/
  -- AUTOR:      FANNY MALAGON
  -- OBJETIVO:   RETORNA UN CURSOR CON LAS RA GIRADAS
  -- RETORNA     CUR_IMPUTACION_GIRADAS
/***************************************************************************/

  FUNCTION FN_IMPUTACION_GIRADAS
 (UN_ENTIDAD     OGT_REGISTRO_PRESUPUESTAL.ENTIDAD%TYPE,
 UN_VIGENCIA_PRESUPUESTO   OGT_REGISTRO_PRESUPUESTAL.VIGENCIA_PRESUPUESTO%TYPE
 ) RETURN CUR_IMPUTACION_GIRADAS;

/***************************************************************************/
  -- AUTOR:      FANNY MALAGON
  -- OBJETIVO:   RETORNA EL VALOR RECHAZADO PARA UN TERCERO DE NOMINA
  -- RETORNA     NUMBER
/***************************************************************************/

  FUNCTION FN_RECHAZOS_NOMINA
 (UN_VIGENCIA   OGT_ANEXO_NOMINA.VIGENCIA%TYPE,
 UN_ENTIDAD    OGT_ANEXO_NOMINA.ENTIDAD%TYPE,
 UN_UNIDAD_EJECUTORA OGT_ANEXO_NOMINA.UNIDAD_EJECUTORA%TYPE,
 UN_TIPO_DOCUMENTO   OGT_ANEXO_NOMINA.TIPO_DOCUMENTO%TYPE,
 UN_CONSECUTIVO    OGT_ANEXO_NOMINA.CONSECUTIVO%TYPE,
 UN_CODIGO_IDENTIFICACION OGT_PROVEEDORES_RA.CODIGO_IDENTIFICACION%TYPE,
 UN_TIPO_IDENTIFICACION  OGT_PROVEEDORES_RA.TIPO_IDENTIFICACION%TYPE
 ) RETURN NUMBER;

/***************************************************************************/
  -- AUTOR:      FANNY MALAGON
  -- OBJETIVO:   ACTUALIZA LOS DATOS DE UNA RA Y UN TERCERO DE LOS PAGOS HECHOS POR RECHAZOS
  -- RETORNA     CERO SINO HAY ERROR O SQLCODE
/***************************************************************************/

  FUNCTION FN_ACTUALIZA_PAGOS_RECHAZOS
 (UN_VIGENCIA   OGT_ANEXO_NOMINA.VIGENCIA%TYPE,
 UN_ENTIDAD    OGT_ANEXO_NOMINA.ENTIDAD%TYPE,
 UN_UNIDAD_EJECUTORA OGT_ANEXO_NOMINA.UNIDAD_EJECUTORA%TYPE,
 UN_TIPO_DOCUMENTO   OGT_ANEXO_NOMINA.TIPO_DOCUMENTO%TYPE,
 UN_CONSECUTIVO    OGT_ANEXO_NOMINA.CONSECUTIVO%TYPE,
 UN_CODIGO_IDENTIFICACION OGT_PROVEEDORES_RA.CODIGO_IDENTIFICACION%TYPE,
 UN_TIPO_IDENTIFICACION  OGT_PROVEEDORES_RA.TIPO_IDENTIFICACION%TYPE,
 UN_OFICIO   OGT_ANEXO_NOMINA.RECHAZO_OFICIO%TYPE,
 UN_FECHA_OFICIO  DATE
 ) RETURN NUMBER;

/***************************************************************************/
  -- AUTOR:      FANNY MALAGON
  -- OBJETIVO:   VALIDA UN REGISTRO DE RA
  -- RETORNA     TRUE O FALSE
/***************************************************************************/

 PROCEDURE PR_VALIDA_REGRA (UN_REG_RA  IN RAREC
        ,UN_PL_ERR    IN OUT ERTAB   -- LISTA DE ERRORES
        ,UN_ABORTE    IN OUT VARCHAR2 -- INDICA SI HAY POR LO MENOS UN ERROR QUE NO PERMITE CARGUE '1'
        ,UN_I         IN OUT NUMBER   -- CONTADOR DE LA TABLA PL
    );

/***************************************************************************/
  -- AUTOR:      FANNY MALAGON
  -- OBJETIVO:   EVALUA SI UNA CADENA ES NUMERICA
  -- RETORNA     TRUE O FALSE
/***************************************************************************/

  FUNCTION OGT_FN_VALIDA_NUMERO (UN_NUMERO VARCHAR2) RETURN BOOLEAN;

END;
/