SELECT
  RTRIM(RH_PERSONAS.PRIMER_APELLIDO) || ' ' || RTRIM(RH_PERSONAS.SEGUNDO_APELLIDO) || ' ' || RTRIM(RH_PERSONAS.NOMBRES) funcionario, 
  RH_PERSONAS.NUMERO_IDENTIFICACION numero_identificacion,
  RH_PERSONAS.TIPO_DOCUMENTO tipo_documento,
  RH_FUNCIONARIO.fecha_ingreso_entidad fecha_ingreso_entidad,
  RH_ENTIDAD.DESCRIPCION fondo_cesantias,
  RH_HISTORICO_NOMINA.NDCAMPO0  VALORCESANTIAS,
  RH_HISTORICO_NOMINA.NDCAMPO1  SUELDO,
  RH_HISTORICO_NOMINA.NDCAMPO2  GASTOSREPRESENTACION,
  RH_HISTORICO_NOMINA.NDCAMPO3  AUXILIOALIMENTACION,
  RH_HISTORICO_NOMINA.NDCAMPO4  SUBSIDIOTRANSPORTE,
  RH_HISTORICO_NOMINA.NDCAMPO5  PRIMANAVIDAD,
  RH_HISTORICO_NOMINA.NDCAMPO6  PRIMAANTIGUEDAD,
  RH_HISTORICO_NOMINA.NDCAMPO7  PRIMASECRETARIAL,
  RH_HISTORICO_NOMINA.NDCAMPO8  PRIMAVACACION,
  RH_HISTORICO_NOMINA.NDCAMPO9  PRIMASEMESTRAL,
  RH_HISTORICO_NOMINA.NDCAMPO10 HORASEXTRAS,
  RH_HISTORICO_NOMINA.NDCAMPO11 VACDINERO,
  RH_HISTORICO_NOMINA.NDCAMPO12 PRIMATECNICA,
  RH_HISTORICO_NOMINA.NDCAMPO13 DIAS,
  RH_HISTORICO_NOMINA.NDCAMPO15 BONIFSERV_QUINQUENIO
FROM
  RH_FUNCIONARIO, RH_PERSONAS,RH_HISTORICO_NOMINA, RH_ENTIDAD
WHERE
  RH_FUNCIONARIO.PERSONAS_INTERNO = RH_PERSONAS.INTERNO_PERSONA
  AND RH_FUNCIONARIO.PERSONAS_INTERNO = NFUNCIONARIO
  AND RH_ENTIDAD.CODIGO=RH_FUNCIONARIO.CODIGO_FONDO_CESANTIAS
  AND RH_ENTIDAD.TIPO=RH_FUNCIONARIO.TIPO_FONDO_CESANTIAS
  AND NHASH = 987789735
  AND BRECHAZADO = 0
  --INI 3909808
  AND RH_FUNCIONARIO.ESTADO_FUNCIONARIO NOT IN (3,5)   -- ljvc DICI 12 2025
  --FIN 3909808
  AND NDCAMPO0 >= 0 -- ljvc DICI 12 2025
  AND DINICIOPERIODO >= 20251201
  AND DFINALPERIODO <=  20251231
  --AND RH_FUNCIONARIO.PERSONAS_INTERNO = 5062
ORDER BY RTRIM(RH_PERSONAS.PRIMER_APELLIDO),RTRIM(RH_PERSONAS.SEGUNDO_APELLIDO),RTRIM(RH_PERSONAS.NOMBRES);
  