PROCEDURE PR_ESTADO IS
BEGIN
	IF TO_NUMBER(SUBSTR(:OGT_RELACION_AUTORIZACION.ESTADO,1,3)||SUBSTR(:OGT_RELACION_AUTORIZACION.ESTADO,10,2))
		 > 0 THEN
  	:OGT_RELACION_AUTORIZACION.DSP_ESTADO := 'INVALIDA';  	
  ELSIF TO_NUMBER(SUBSTR(:OGT_RELACION_AUTORIZACION.ESTADO,1,3)||SUBSTR(:OGT_RELACION_AUTORIZACION.ESTADO,10,2))
		 = 0 THEN
  	:OGT_RELACION_AUTORIZACION.DSP_ESTADO := 'VALIDA';	
  END IF;  	
	IF SUBSTR(:OGT_RELACION_AUTORIZACION.ESTADO,9,1) = '1' THEN
  	:OGT_RELACION_AUTORIZACION.DSP_ESTADO := 'ANULADA';	  	
	ELSIF SUBSTR(:OGT_RELACION_AUTORIZACION.ESTADO,8,1) = '1' THEN
  	:OGT_RELACION_AUTORIZACION.DSP_ESTADO := 'GIRADA';	
	ELSIF SUBSTR(:OGT_RELACION_AUTORIZACION.ESTADO,7,1) = '1' THEN
  	:OGT_RELACION_AUTORIZACION.DSP_ESTADO := 'DEVUELTA';	
	ELSIF SUBSTR(:OGT_RELACION_AUTORIZACION.ESTADO,6,1) = '1' THEN
  	:OGT_RELACION_AUTORIZACION.DSP_ESTADO := 'RADICADA';	
	ELSIF SUBSTR(:OGT_RELACION_AUTORIZACION.ESTADO,5,1) = '1' THEN
  	:OGT_RELACION_AUTORIZACION.DSP_ESTADO := 'ENVIADA';	
  ELSIF	SUBSTR(:OGT_RELACION_AUTORIZACION.ESTADO,4,1) = '1' THEN
  	:OGT_RELACION_AUTORIZACION.DSP_ESTADO := 'FIRMADA';	
	END IF;                                															        		 	
EXCEPTION WHEN OTHERS THEN
	PR_DESPLIEGA_MENSAJE('AL_STOP_1','Ocurrio el siguiente error en PR_ESTADO '||SQLERRM);
	RAISE FORM_TRIGGER_FAILURE;

SELECT * --, SUBSTR(ESTADO,1,3) --||SUBSTR(ESTADO,10,2) EL_ESTADO
 FROM 
--UPDATE 
OGT_RELACION_AUTORIZACION
 --SET ESTADO = '00000000000'
WHERE VIGENCIA=2026 AND MES=1 AND TIPO_DOCUMENTO = 'RA' AND CONSECUTIVO=1;

COMMIT;

--