
SELECT * FROM ALL_USERS
WHERE USERNAME IN ('SL')
;

SELECT * FROM DBA_ROLES
WHERE ROLE LIKE 'OGT_ADMIN'
;

SELECT * FROM DBA_ROLE_PRIVS
WHERE GRANTED_ROLE = 'OGT_ADMIN'
AND GRANTEE = 'SL'
;


SELECT * FROM DBA_SYS_PRIVS
WHERE GRANTEE = 'OGT_ADMIN'
ORDER BY 1,2
;

SELECT * FROM ALL_TAB_PRIVS
WHERE GRANTEE = 'OGT_ADMIN'
AND TABLE_NAME = 'OGT_DOCUMENTO'