		-- Y PARA LAS QUE CORRESPONDEN A EL USUARIO QUE SE CONECTA INDICA UNO(1) PARA DECIR QUE HAY QUE ACTIVAR Y CERO (0) PARA DESACTIVAR
    	
    SELECT /*+ RULE*/M.CODIGO, M.OPCION_MENU, DECODE(nvl(mub.cod_menopc,0),0,0,1) ACTIVA
			  FROM TRC_MENU_OPCION M, 
			      (SELECT DISTINCT MU.COD_MENOPC
			          FROM TRC_MENU_USUARIO MU
			         WHERE TRUNC(SYSDATE) BETWEEN MU.FECHA_INICIAL AND NVL(MU.FECHA_FINAL,TRUNC(SYSDATE))) MUS ,
			       TRC_MENU_USUARIO MUB         
			WHERE M.MENU_PADRE   = UN_MOMBRE_MENU -- ESTA CONDICION ES PARA ACTIVAR SOLO LAS OPCIONES DEL MENU PRINCIPAL
			  AND MUS.COD_MENOPC = M.CODIGO   
			  AND MI_USUARIO     = MUB.USUARIO   (+)
			  AND M.CODIGO       = MUB.COD_MENOPC(+)

-- CURSOR QUE RETORNA EL PATH DE LA OPCION DE MENU PARA ACTIVAR TODO EL CAMINO	  
    CURSOR C_PATH_OPC IS
			 SELECT  M.CODIGO, M.OPCION_MENU
			   FROM TRC_MENU_OPCION M
			  START WITH M.CODIGO = MI_COD_OPCMEN
			CONNECT BY PRIOR  M.COD_MENANT = m.CODIGO;              

	  SELECT *
			  FROM  bintablas bin
			 WHERE bin.grupo = 'TERCEROS'
		     AND bin.nombre = 'FUNCIONARIO_TER' 
			   AND (BIN.VIG_FINAL IS NULL OR BIN.VIG_FINAL >= trunc(SYSDATE))
			   AND BIN.ARGUMENTO in ('AFORTEGON','VVARGASN') -- MI_USUARIO
			   AND ROWNUM = 1			;            

     INSERT INTO BINTABLAS (GRUPO,NOMBRE,ARGUMENTO,RESULTADO,VIG_INICIAL)
     VALUES ('TERCEROS','FUNCIONARIO_TER','VVARGASN','VVARGASN','28/JAN/2026')          

     COMMIT;

SELECT * from
--     UPDATE 
BINTABLAS bin
--SET VIG_INICIAL = '28/JAN/2026'
     WHERE grupo = 'TERCEROS'
		     AND bin.nombre = 'FUNCIONARIO_TER' 
			   --AND (BIN.VIG_FINAL IS NULL OR BIN.VIG_FINAL >= trunc(SYSDATE))
			   AND BIN.ARGUMENTO = 'VVARGASN'