/*  INT     CC
    509     24182848
    */
select -- /*
     CASE ESTADO 
     WHEN '1' THEN 'NUEVO'
     WHEN '2' THEN 'ACTIVO'
     WHEN '3' THEN 'CANCELADO'
     WHEN '4' THEN 'SUSPENDIDO'
     WHEN '5' THEN 'TERMINADO'
     ELSE 'OTRO'
     END AS ESTADONOM   --*/
     , RH_DESCUENTOS_F.BENEFICIARIO,
        RH_DESCUENTOS_F.TIPO,
        RH_DESCUENTOS_F.NUMERO_DESCUENTO,
        RH_DESCUENTOS_F.FECHA_INICIO,
        RH_DESCUENTOS_F.PERIODICIDAD,
        RH_DESCUENTOS_F.FECHA_INICIAL_CORTE,
        RH_DESCUENTOS_F.CLASE,
        RH_DESCUENTOS_F.MONTO,
        RH_DESCUENTOS_F.IDENTIFICACION_DESCUENTO
from RH_DESCUENTOS_F
where funcionario = 509
and tipo = 'LIBRANZA'
AND fecha_inicio = '07/feb/2025'
;

select *
from RH_DETALLE_PAGOS_F
where funcionario = 509
and DESCUENTOS_TIPO = 'LIBRANZA'
and descuentos_numero in (4,5)