
SELECT * FROM ALL_USERS
WHERE USERNAME IN ('XPBOHORQUEZ')
;

SELECT * FROM DBA_ROLES
WHERE ROLE LIKE 'OGT%'
;

--
--'ARVANEGAS' --req 3325713
--'JSERRANO' --req 3157760  Jhuveli Andrea Serrano  Deb�a ser JASERRANO.
--'='DOCAMPO'  --req 3155096  Darley Ocampo Garcia
--LIKE 'SMBARAJAS'  --req 3185097 SANDRA MILENA BARAJAS GUATAQUIRA
                  --REQ 3286660 20220726 SANDRA MILENA BARAJAS
--COMOLANO 3452897-2023 CLAUDIA OFELIA MOLANO VARGAS.                         PERNO
--EORTIZ,  OIALFONSO 3474458-2023 ERNESTO ORTIZ ALARCON
--DPCALDERON, 3482332
;
--set echo off

SELECT * FROM DBA_SYS_PRIVS
WHERE GRANTEE IN ('XPBOHORQUEZ')
ORDER BY 1,2
;

SELECT * FROM USER_SYS_PRIVS
WHERE PRIVILEGE LIKE '%EXECUTE%'
ORDER BY 1,2
;


SELECT * /*GRANTED_ROLE*/ FROM DBA_ROLE_PRIVS
WHERE GRANTEE = 'XPBOHORQUEZ'
AND GRANTED_ROLE LIKE 'OGT%'
MINUS
SELECT GRANTED_ROLE FROM DBA_ROLE_PRIVS
WHERE GRANTEE = 'DVEGA'
ORDER BY GRANTED_ROLE
;

SELECT * FROM ALL_TAB_PRIVS
WHERE TABLE_SCHEMA = 'OGT'
AND PRIVILEGE = 'EXECUTE'
AND TABLE_NAME LIKE 'OGT%'
AND GRANTEE LIKE 'OGT_ADMIN%'
ORDER BY GRANTEE 
;


SELECT * FROM ALL_TAB_PRIVS
WHERE GRANTEE = 'VVARGASN'
MINUS
SELECT * FROM ALL_TAB_PRIVS
WHERE GRANTEE = 'YORDUNA'
ORDER BY TABLE_NAME
;

SELECT tablespace_name, 
       round(used_mbytes) as used_mb, 
       round(free_mbytes) as free_mb
FROM dev_ts_usage_metrics;

select *
from pr_v_rubros
where vigencia = 2026 and interno_rubro in (1843)

