
SELECT * FROM ALL_USERS
WHERE USERNAME IN ('XPBOHORQUEZ')
;

SELECT * FROM DBA_ROLES
WHERE ROLE LIKE 'OGT%'
;

--
--'ARVANEGAS' --req 3325713
--'JSERRANO' --req 3157760  Jhuveli Andrea Serrano  Deb�a ser JASERRANO.
--'='DOCAMPO'  --req 3155096  Darley Ocampo Garcia
--LIKE 'SMBARAJAS'  --req 3185097 SANDRA MILENA BARAJAS GUATAQUIRA
                  --REQ 3286660 20220726 SANDRA MILENA BARAJAS
--COMOLANO 3452897-2023 CLAUDIA OFELIA MOLANO VARGAS.                         PERNO
--EORTIZ,  OIALFONSO 3474458-2023 ERNESTO ORTIZ ALARCON
--DPCALDERON, 3482332
;
--set echo off

SELECT * FROM DBA_SYS_PRIVS
WHERE GRANTEE IN ('XPBOHORQUEZ')
ORDER BY 1,2
;


SELECT * /*GRANTED_ROLE*/ FROM DBA_ROLE_PRIVS
WHERE GRANTEE = 'XPBOHORQUEZ'
AND GRANTED_ROLE LIKE 'OGT%'
MINUS
SELECT GRANTED_ROLE FROM DBA_ROLE_PRIVS
WHERE GRANTEE = 'DVEGA'
ORDER BY GRANTED_ROLE
;

SELECT * FROM ALL_TAB_PRIVS
WHERE TABLE_SCHEMA = 'OGT'
AND TABLE_NAME IN ('OGT_DOCUMENTO','OGT_DETALLE_DOCUMENTO','OGT_PK_INGRESO')
AND GRANTEE LIKE 'OGT_ADMIN%'
ORDER BY GRANTEE 
;


SELECT * FROM ALL_TAB_PRIVS
WHERE GRANTEE = 'NEACOSTA'
MINUS
SELECT * FROM ALL_TAB_PRIVS
WHERE GRANTEE = 'YORDUNA'
ORDER BY TABLE_NAME
;

